### ISSUE TITLE
Multi-Language Translation Support

### ISSUE THREAD

**Issue by q1085909155** [Riotline/rl-chatkilllogs#1]
Can you give me some more translation documents
I want more phrases

**Comment by xg29763** [comment]
What are you in the market for in terms of translations. Would you like a full  translation list of all outputs.

**Comment by q1085909155** [comment]
I need a Chinese translation

**Comment by Riotline** [comment]
I see. I wasn't originally developing for the public however since it is released I suppose I should implement multi-language support.
I'll try my best to bring it through as soon as possible!

**Comment by q1085909155** [comment]
Well, thank you. I hope you can finish it as soon as possible. I really need it now

**Comment by Riotline** [comment]
Updated the plugin with multi-language support; however, it has not been tested so try it out and create a new issue report if it is not working.
